apiVersion: v1
kind: Service
metadata:
  name: wa-paymentsgatewayapi-service
spec:
  selector:
    app: wa-paymentsgatewayapi
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer