apiVersion: apps/v1
kind: Deployment
metadata:
  name: wa-paymentsgatewayapi-deployment
spec:
  template:
    metadata:
      name: wa-paymentsgatewayapi
      labels:
        app: wa-paymentsgatewayapi
    spec:
      containers:
        - name: wa-paymentsgatewayapi-container
          image: 659767469388.dkr.ecr.us-east-1.amazonaws.com/wa-fastfood/wa-fastfoodselfservice.payments_gateway_api:latest
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: wa-paymentsgatewayapi-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 5003
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 5003
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m
  replicas: 2
  selector:
    matchLabels:
      app: wa-paymentsgatewayapi