// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UnitTests.Features.Payments
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ObterStatusDePagamentoFeature : object, Xunit.IClassFixture<ObterStatusDePagamentoFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetPaymentStatus.feature"
#line hidden
        
        public ObterStatusDePagamentoFeature(ObterStatusDePagamentoFeature.FixtureData fixtureData, UnitTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Payments", "Obter Status de Pagamento", "  Como um usu�rio do sistema,\r\n  Eu quero consultar o status de pagamento de um p" +
                    "edido,\r\n  Para que eu possa saber se o pagamento foi aprovado, pendente ou outro" +
                    " status.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
  #line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deveria retornar o status de pagamento quando o pagamento existe")]
        [Xunit.TraitAttribute("FeatureTitle", "Obter Status de Pagamento")]
        [Xunit.TraitAttribute("Description", "Deveria retornar o status de pagamento quando o pagamento existe")]
        public void DeveriaRetornarOStatusDePagamentoQuandoOPagamentoExiste()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deveria retornar o status de pagamento quando o pagamento existe", @"    Dado que existe um pagamento aprovado com o OrderId 123
    Quando eu consultar o status de pagamento para o pedido com OrderId 123
    Ent�o o status do pagamento deve ser ""Aprovado""
    E o n�mero do pedido deve ser ""12345""
    E a data de processamento do pagamento deve ser uma data v�lida", tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deveria retornar nulo quando o pagamento n�o existir")]
        [Xunit.TraitAttribute("FeatureTitle", "Obter Status de Pagamento")]
        [Xunit.TraitAttribute("Description", "Deveria retornar nulo quando o pagamento n�o existir")]
        public void DeveriaRetornarNuloQuandoOPagamentoNOExistir()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deveria retornar nulo quando o pagamento n�o existir", "    Dado que n�o existe nenhum pagamento com o OrderId 999\r\n    Quando eu consult" +
                    "ar o status de pagamento para o pedido com OrderId 999\r\n    Ent�o o status de pa" +
                    "gamento deve ser nulo", tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
  this.FeatureBackground();
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ObterStatusDePagamentoFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ObterStatusDePagamentoFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
